package Wollokito.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import java.util.Map;
import jetbrains.mps.smodel.adapter.ids.SReferenceLinkId;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsDescriptor;
import java.util.HashMap;
import jetbrains.mps.smodel.runtime.base.BaseReferenceConstraintsDescriptor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.runtime.ReferenceScopeProvider;
import jetbrains.mps.smodel.runtime.base.BaseScopeProvider;

public class MethodCall_Constraints extends BaseConstraintsDescriptor {
  public MethodCall_Constraints() {
    super(MetaIdFactory.conceptId(0x4715934d95da4083L, 0xa4169de3deb57b4cL, 0x690c90435eefa3b9L));
  }
  @Override
  protected Map<SReferenceLinkId, ReferenceConstraintsDescriptor> getNotDefaultSReferenceLinks() {
    Map<SReferenceLinkId, ReferenceConstraintsDescriptor> references = new HashMap<SReferenceLinkId, ReferenceConstraintsDescriptor>();
    references.put(MetaIdFactory.refId(0x4715934d95da4083L, 0xa4169de3deb57b4cL, 0x690c90435eefa3b9L, 0x690c90435eefa4a8L), new BaseReferenceConstraintsDescriptor(MetaIdFactory.refId(0x4715934d95da4083L, 0xa4169de3deb57b4cL, 0x690c90435eefa3b9L, 0x690c90435eefa4a8L), this) {
      @Nullable
      @Override
      public ReferenceScopeProvider getScopeProvider() {
        return new BaseScopeProvider() {};
      }
    });
    return references;
  }
}
