package Wollokito.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;

public abstract class Expression_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Expression_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "Wollokito.structure.Expression";
  }
  public abstract String virtual_evaluate_7569583692733018617(SNode thisNode);
}
