package Wollokito.behavior;

/*Generated by MPS */

import jetbrains.mps.scope.FilteringScope;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.scope.Scope;
import org.jetbrains.mps.openapi.model.SNode;

public class MethodCallScope extends FilteringScope {

  public final SAbstractConcept declaration;

  public MethodCallScope(Scope scope, SAbstractConcept declaration) {
    super(scope);
    this.declaration = declaration;
  }


  @Override
  public boolean isExcluded(SNode node) {
    return super.isExcluded(node);
  }

}
