package Wollokito.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

public class MethodCall_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public MethodCall_BehaviorDescriptor() {
  }
  public String virtual_evaluate_7569583692733018617(SNode thisNode) {
    return MethodCall_Behavior.virtual_evaluate_7569583692733018617(thisNode);
  }
  @Override
  public String getConceptFqName() {
    return "Wollokito.structure.MethodCall";
  }
}
