package Wollokito.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class MethodCall_Behavior {
  public static void init(SNode thisNode) {
  }
  public static String virtual_evaluate_7569583692733018617(SNode thisNode) {
    return BehaviorReflection.invokeVirtual(String.class, SLinkOperations.getTarget(SLinkOperations.getTarget(thisNode, MetaAdapterFactory.getReferenceLink(0x4715934d95da4083L, 0xa4169de3deb57b4cL, 0x690c90435eefa3b9L, 0x690c90435eefa4a8L, "message")), MetaAdapterFactory.getContainmentLink(0x4715934d95da4083L, 0xa4169de3deb57b4cL, 0x690c90435eefa3b6L, 0x690c90435eefa3c4L, "expression")), "virtual_evaluate_7569583692733018617", new Object[]{});
  }
}
