package Wollokito.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.internal.collections.runtime.IterableUtils;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.internal.collections.runtime.ISelector;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class Program_Behavior {
  public static void init(SNode thisNode) {
  }
  public static String call_mensajeDeObjetosInexistentes_7569583692732862079(SNode thisNode) {
    return "No hay objetos definidos : )";
  }
  public static String call_nombresDeMisObjetos_7569583692732894113(SNode thisNode) {
    return IterableUtils.join(ListSequence.fromList(SLinkOperations.getChildren(thisNode, MetaAdapterFactory.getContainmentLink(0x4715934d95da4083L, 0xa4169de3deb57b4cL, 0x690c90435eeb6cceL, 0x690c90435eec0f6aL, "objectDefinitions"))).select(new ISelector<SNode, String>() {
      public String select(SNode it) {
        return SPropertyOperations.getString(it, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
      }
    }), ", ");
  }
}
